tasks:
  - init: |
      go get && go build ./... && go test ./... && make
      mkdir ~/.cliche
      wget https://raw.githubusercontent.com/nbd-wtf/cliche/master/src/main/resources/reference.conf -O ~/.cliche/cliche.conf
      sed -i '8i  seed = "acid lunch arrange dish spin tumble price frequent turtle motion engage flat"' ~/.cliche/cliche.conf
    command: SERVICE_URL="https://3003-$(echo $GITPOD_WORKSPACE_URL | cut -f3 -d/)" PORT=3003 TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN DATABASE_URL="user=postgres password=Pass2020! sslmode=disable" REDIS_URL="redis://localhost:6379" CLICHE_DATADIR="/home/gitpod/.cliche" CLICHE_JAR_PATH="/workspace/cliche.jar" PROXY_ACCOUNT="123" go run .

  - init: |
        cd /workspace
        wget https://github.com/nbd-wtf/cliche/releases/download/v0.4.7/cliche.jar
    command: |
        docker run -d --name dev-postgres -e POSTGRES_PASSWORD=Pass2020! -v ${HOME}/postgres-data/:/var/lib/postgresql/data -p 5432:5432 postgres
        psql -h localhost -U postgres -f /workspace/lntxbot/postgres.sql
        docker run -d --name redis-stack-server -p 6379:6379 redis/redis-stack-server:latest
    
# notes
# replace xxx TELEGRAM_BOT_TOKEN or use gp env TELEGRAM_BOT_TOKEN="xxx"
# no need to start cliche seperately
# java -Dcliche.seed="acid lunch arrange dish spin tumble price frequent turtle motion engage flat" -jar cliche.jar
# docker run -d -p 8080:80 -p 8443:443 --rm -t mendhak/http-https-echo

